apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: my-python-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8017
        env:
        - name: MY_WEB_APP_STATUS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MY_WEB_APP_STATUS
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - port: 80
      targetPort: 8017
      nodePort: 30080
